- .circleci/config.yml
https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-186
Renaming deployment pipeline
> Set up deployment pipeline

- PersonApi/serverless.yml
Updated serverless.yml to include:
- creation of SG for API
- point to the correct VPC and subnets in the respective accounts
> Update Lamda vpc config

- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
https://hackney.atlassian.net/browse/MTTL-538
Update the Gateway class tests so that they use a real DynamoDb instance where possible.
> Functional gateway tests now use real DynamoDb instance

- PersonApi/Startup.cs
- PersonApi/serverless.yml
https://hackney.atlassian.net/browse/MTTL-611
Enabling CORS for Persons API
> MTTL-611 Added CORS

- PersonApi.Tests/V1/Domain/PersonTests.cs
- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/Factories/EntityFactoryTest.cs
- PersonApi.Tests/V1/Factories/ResponseFactoryTest.cs
- PersonApi.Tests/V1/Helper/Constants.cs
- PersonApi/V1/Boundary/Response/PersonResponseObject.cs
- PersonApi/V1/Domain/Person.cs
- PersonApi/V1/Domain/Tenure.cs
- PersonApi/V1/Factories/EntityFactory.cs
- PersonApi/V1/Factories/ResponseFactory.cs
- PersonApi/V1/Infrastructure/PersonDbEntity.cs
https://hackney.atlassian.net/browse/MTTL-525
Adding the tenure property to the person response object
> MTTL-525_AddTenureInformationToPerson

- PersonApi.Tests/V1/Helper/Constants.cs
- PersonApi/V1/Domain/Tenure.cs
https://hackney.atlassian.net/browse/MTTL-640
Bug in parsing string to datetimes in dynamodb
> MTTL-640 Changed datetime to string to avoid dynamodb issues

- terraform/development/main.tf
- terraform/production/main.tf
- terraform/staging/main.tf
https://hackney.atlassian.net/browse/MTTL-665
Create an SNS topic
> MTTL-665 Added SNS topic to terraform files

- PersonApi.Tests/V1/Helper/Constants.cs
- PersonApi/V1/Domain/Enums.cs
https://hackney.atlassian.net/browse/MTTL-707
Updated PersonType enum values.
> Updated PersonType values

- terraform/development/dynamodb.tf
- terraform/production/dynamodb.tf
- terraform/staging/dynamodb.tf
solving pipeline issue with dynamodb resource
> solving pipeline issue with dynamodb resource

- PersonApi/V1/Domain/Enums.cs
The title enum object has been updated with the following:
- Dr
- Master
- Miss
- Mr
- Mrs
- Ms
- Other
- Rabbi
- Reverend
> updated title enum to include all titles

- PersonApi/serverless.yml
[https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-782](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-782)
Experimenting on provisioning AWS AppConfig using cloud formation
> cloudformation for app-config

- PersonApi/serverless.yml
I've updated the deployment strategy to replicate the `AllAtOnce` strategy
> deployment strategy updated

- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi/V1/Boundary/Request/PersonRequestObject.cs
- PersonApi/V1/Boundary/Response/PersonResponseObject.cs
- PersonApi/V1/Domain/Person.cs
- PersonApi/V1/Infrastructure/PersonDbEntity.cs
https://hackney.atlassian.net/browse/MTTL-863
Made the Gender enum property optional
> Made the Gender property optional

- PersonApi.Tests/AwsMockWebApplicationFactory.cs
- PersonApi/Startup.cs
- docker-compose.yml
> Person release

- PersonApi.Tests/V1/Boundary/Validation/PersonRequestObjectValidatorTests.cs
- PersonApi/V1/Boundary/Request/Validation/PersonRequestObjectValidator.cs
https://hackney.atlassian.net/browse/MTTL-910
> Corrected validation for null gender value

- PersonApi.Tests/ContentHelper.cs
- PersonApi.Tests/GlobalSuppressions.cs
- PersonApi.Tests/V1/Boundary/Validation/PersonRequestObjectValidatorTests.cs
- PersonApi.Tests/V1/Controllers/PersonApiControllerTests.cs
- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/UpdatePersonByIdE2ETests.cs
- PersonApi.Tests/V1/Factories/ResponseFactoryTest.cs
- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi.Tests/V1/UseCase/UpdatePersonByIdUseCaseTests.cs
- PersonApi/Startup.cs
- PersonApi/V1/Boundary/Request/Validation/PersonRequestObjectValidator.cs
- PersonApi/V1/Boundary/Response/PersonResponseObject.cs
- PersonApi/V1/Controllers/PersonApiController.cs
- PersonApi/V1/Factories/ResponseFactory.cs
- PersonApi/V1/Gateways/DynamoDbGateway.cs
- PersonApi/V1/Gateways/IPersonApiGateway.cs
- PersonApi/V1/UseCase/Interfaces/IUpdatePersonUseCase.cs
- PersonApi/V1/UseCase/UpdatePersonUseCase.cs
https://hackney.atlassian.net/browse/MTTL-910
https://hackney.atlassian.net/browse/MTTL-791
> Release mttl 910

- PersonApi.Tests/V1/Boundary/Validation/TenureValidatorTests.cs
- PersonApi/V1/Boundary/Request/Validation/TenureValidator.cs
- PersonApi/V1/Domain/Tenure.cs
https://hackney.atlassian.net/browse/MTTL-906
> Added new properties for API

- PersonApi.Tests/V1/Infrastructure/EntityUpdaterTests.cs
- PersonApi/V1/Infrastructure/EntityUpdater.cs
- PersonApi/V1/Infrastructure/UpdateEntityResult.cs
https://hackney.atlassian.net/browse/MTTL-1034
Relaxed restrictions on unknown properties during update
> Relaxed restrictions on unknown properties during update

- PersonApi.Tests/V1/Controllers/PersonApiControllerTests.cs
- PersonApi.Tests/V1/E2ETests/Fixtures/PersonFixture.cs
- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi.Tests/V1/UseCase/GetByIdUseCaseTests.cs
- PersonApi/V1/Controllers/PersonApiController.cs
- PersonApi/V1/Domain/Person.cs
- PersonApi/V1/Factories/EntityFactory.cs
- PersonApi/V1/Factories/IResponseFactory.cs
- PersonApi/V1/Infrastructure/PersonDbEntity.cs
- PersonApi/V1/UseCase/GetByIdUseCase.cs
- PersonApi/V1/UseCase/Interfaces/IGetByIdUseCase.cs
- README.md
https://hackney.atlassian.net/browse/MTTL-818.
Push changes to staging
> Release mttl 818

- PersonApi.Tests/V1/Domain/TenureHelpersTests.cs
- PersonApi.Tests/V1/E2ETests/Steps/PostPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/Stories/PostPersonTests.cs
- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi/V1/Domain/Tenure.cs
- PersonApi/V1/Domain/TenureHelpers.cs
https://hackney.atlassian.net/browse/MTTL-1120
Corrects the calculation and (non) storage of the tenure IsActive flag
> Correct tenure IsActive use

- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/Factories/ResponseFactoryTest.cs
- PersonApi/V1/Boundary/Response/PersonResponseObject.cs
- PersonApi/V1/Boundary/Response/TenureResponseObject.cs
- PersonApi/V1/Factories/ResponseFactory.cs
https://hackney.atlassian.net/browse/MTTL-1120
Ensure tenure IsActive flag is actually returned by the GET api
> Added TenureResponseObject

- PersonApi.Tests/V1/Domain/TenureHelpersTests.cs
- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/Steps/PostPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/Stories/PostPersonTests.cs
- PersonApi.Tests/V1/Factories/ResponseFactoryTest.cs
- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi/V1/Boundary/Response/PersonResponseObject.cs
- PersonApi/V1/Boundary/Response/TenureResponseObject.cs
- PersonApi/V1/Domain/Tenure.cs
- PersonApi/V1/Domain/TenureHelpers.cs
- PersonApi/V1/Factories/ResponseFactory.cs
Push tenure IsActive fixes to Staging/Production
> Release mttl 1120

- PersonApi/V1/Domain/User.cs
- PersonApi/V1/Factories/PersonSnsFactory.cs
https://hackney.atlassian.net/browse/MTTL-1096
> Removed user id from raised events

- PersonApi.Tests/V1/Infrastructure/JWT/TokenFactoryTests.cs
- PersonApi/PersonApi.csproj
- PersonApi/Startup.cs
https://hackney.atlassian.net/browse/MTTL-1119.
> Updated Hackney.Core package version

- CODEOWNERS
- PersonApi.Tests/V1/Infrastructure/JWT/TokenFactoryTests.cs
- PersonApi/PersonApi.csproj
- PersonApi/Startup.cs
- PersonApi/V1/Domain/User.cs
- PersonApi/V1/Factories/PersonSnsFactory.cs
Release logging changes to staging
> Release mttl 1101

- PersonApi.Tests/V1/E2ETests/Fixtures/PersonFixture.cs
- PersonApi.Tests/V1/E2ETests/Steps/PostPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/Steps/UpdatePersonStep.cs
- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi/V1/Domain/Person.cs
- PersonApi/V1/Factories/EntityFactory.cs
- PersonApi/V1/Gateways/DynamoDbGateway.cs
- PersonApi/V1/Infrastructure/PersonDbEntity.cs
https://hackney.atlassian.net/browse/MTTL-1234.
Added LastModified property to person domain/db models
> Added LastModified property to person domain/db models

- terraform/development/dynamodb.tf
- terraform/development/main.tf
- terraform/development/variables.tf
- terraform/production/dynamodb.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/staging/dynamodb.tf
- terraform/staging/main.tf
- terraform/staging/variables.tf
https://hackney.atlassian.net/browse/MTTL-1461
Get metrics in an easy to view dashboard
Added Cloudwatch dashboard.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.
> added cloudwatch dashboard TF module

- terraform/development/dynamodb.tf
- terraform/development/main.tf
- terraform/development/variables.tf
- terraform/production/dynamodb.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/staging/dynamodb.tf
- terraform/staging/main.tf
- terraform/staging/variables.tf
* added cloudwatch dashboard TF module
* updated tags
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.
> Deploy to Staging

- PersonApi.Tests/V1/Boundary/Validation/CreatePersonRequestObjectValidatorTests.cs
- PersonApi/V1/Domain/Enums.cs
https://hackney.atlassian.net/browse/MTTL-1601
> Updated PersonType enum values.

- .circleci/config.yml
- .gitignore
- CODEOWNERS
- PersonApi.Tests/V1/Boundary/Validation/CreatePersonRequestObjectValidatorTests.cs
- PersonApi.Tests/V1/Controllers/PersonApiControllerTests.cs
- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/Steps/UpdatePersonStep.cs
- PersonApi.Tests/V1/Factories/PersonSnsFactoryTests.cs
- PersonApi.Tests/V2/Controllers/PersonApiControllerTests.cs
- PersonApi.Tests/V2/E2ETests/Steps/BaseSteps.cs
- PersonApi.Tests/V2/E2ETests/Steps/PostPersonSteps.cs
- PersonApi.Tests/V2/E2ETests/Stories/PostPersonTests.cs
- PersonApi.Tests/V2/Factories/PersonSnsFactoryTests.cs
- PersonApi.Tests/V2/UseCase/PostNewPersonUseCaseTests.cs
- PersonApi.sln
- PersonApi/Dockerfile
- PersonApi/PersonApi.csproj
- PersonApi/Startup.cs
- PersonApi/V1/Controllers/PersonApiController.cs
- PersonApi/V1/Domain/Enums.cs
- PersonApi/V2/Controllers/PersonApiController.cs
- PersonApi/V2/Factories/ISnsFactory.cs
- PersonApi/V2/Factories/PersonSnsFactory.cs
- PersonApi/V2/Infrastructure/CreateEventConstants.cs
- PersonApi/V2/UseCase/Interfaces/IPostNewPersonUseCase.cs
- PersonApi/V2/UseCase/PostNewPersonUseCase.cs
- docker-compose.yml
> Release mttl 1016

- .circleci/config.yml
- PersonApi.Tests/V1/E2ETests/Steps/PostPersonSteps.cs
- PersonApi.Tests/V1/E2ETests/Steps/UpdatePersonStep.cs
- PersonApi.Tests/V2/E2ETests/Steps/PostPersonSteps.cs
> Removed unnecessary line

- PersonApi/Startup.cs
- PersonApi/serverless.yml
https://hackney.atlassian.net/browse/MTTL-1167.
Added x-correlation-id header
> Added x-correlation-id header

- .circleci/config.yml
- terraform/development/terraform-compliance/dynamodb.feature
- terraform/development/terraform-compliance/sns.feature
- terraform/production/terraform-compliance/dynamodb.feature
- terraform/production/terraform-compliance/sns.feature
- terraform/staging/terraform-compliance/dynamodb.feature
- terraform/staging/terraform-compliance/sns.feature
[Add a link to the JIRA ticket that the changes in this PR describe.](https://hackney.atlassian.net/browse/MTTL-1927)
Added Terraform compliance rules to enforce Terraform guidelines
Added TF compliance rules 
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
Are there any next steps that need to addressed after merging this PR? Add them here.
> added Terraform compliance rules

- PersonApi.Tests/V1/E2ETests/Steps/GetPersonSteps.cs
- PersonApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- PersonApi/PersonApi.csproj
https://hackney.atlassian.net/browse/MTTL-2040
Updated Person shared package version to include the new IsAMinor property
> Updated Person shared package version

- .circleci/config.yml
[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2363)
Removed deprecated --account flag
> Removed --account flag

- .circleci/config.yml
- PersonApi/serverless.yml
[JIRA](https://hackney.atlassian.net/browse/MTTL-2406)
- update config.yml and serverless.yml to be enabled WAF
> Enable WAF

- .circleci/config.yml
Made SSM parameter for Pact Broker password environment-specific to configure it on staging
> Environment-specific PactBrokerUserPassword parameter

- .circleci/config.yml
- PersonApi/policies/require-authorizer.js
- PersonApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-2412)
> Enable serverless safeguards

- .circleci/config.yml
Reordered staging workflow to let build-and-test step read SSM parameters
> reorder staging workflow to let build-and-test read SSM parameters

- PersonApi.Tests/MockWebApplicationFactory.cs
- PersonApi.Tests/PactBroker/PersonPactBrokerFixture.cs
- PersonApi.Tests/PersonApi.Tests.csproj
- PersonApi.Tests/V1/E2ETests/Fixtures/PersonFixture.cs
- PersonApi.Tests/V1/E2ETests/Stories/PostPersonTests.cs
- PersonApi.Tests/V1/E2ETests/Stories/UpdatePersonTests.cs
- PersonApi.Tests/V2/E2ETests/Stories/PostPersonTests.cs
- docker-compose.yml
https://hackney.atlassian.net/browse/MTTL-2869
Upgrade `Hackney.Core.Testing.Sns` version to fix bug where tests are falsely passing.
> MTTL-2869: Upgrade Hackney.Core.Testing.Sns version

- .circleci/config.yml
Fix terraform compliance checks failing & run tf compliance checks on all branches
> Bugfix pipeline

- .circleci/config.yml
- PersonApi.Tests/Dockerfile
https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?assignee=624c20c6a629c30068a81020&selectedIssue=MTTL-2956
Resolve SonarCloud Issues
> SonarCloud Issue

- .circleci/config.yml
- PersonApi.Tests/Dockerfile
- PersonApi.Tests/PersonApi.Tests.csproj
- PersonApi/Dockerfile
- PersonApi/PersonApi.csproj
- PersonApi/Startup.cs
- PersonApi/build.cmd
- PersonApi/build.sh
- PersonApi/serverless.yml
https://hackney.atlassian.net/browse/MTTL-3267
Update API to .NET 6 as .NET 3.1 is deprecated.
> Update to .net 6

- PersonApi.Tests/V1/E2ETests/Fixtures/PersonFixture.cs
- PersonApi.Tests/V1/E2ETests/Stories/PostPersonTests.cs
- PersonApi/PersonApi.csproj
Update Shared NuGet Package to allow a person to be created without DOB and title when personType is Housing Officer or Housing Area Manager
> update nuget package and add new test

- .circleci/config.yml
- Makefile
- PersonApi.Tests/Dockerfile
- PersonApi.Tests/MockWebApplicationFactory.cs
- PersonApi.Tests/PersonApi.Tests.csproj
- PersonApi.Tests/V1/Controllers/BaseControllerTests.cs
- PersonApi/Dockerfile
- PersonApi/PersonApi.csproj
- PersonApi/V1/Controllers/PersonApiController.cs
- PersonApi/build.cmd
- PersonApi/build.sh
- PersonApi/serverless.yml
[HPT-606](https://hackney.atlassian.net/browse/HPT-606) Upgrade APIs to Dotnet 8
[HPT-606]: https://hackney.atlassian.net/browse/HPT-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Upgrade API to Dotnet 8

- PersonApi/serverless.yml
Update staging lambda authorizer
- Hardcode authorizer ARNs in serverless, preventing any unintended changes via parameter store
- Update staging authorizer to the new version
> Update dev and staging lambda authorizer

- PersonApi/serverless.yml
Updated production authorizer ARN
> Update production authorizer ARN

- PersonApi/serverless.yml
> Fix merge conflicts from  'origin/release'

- PersonApi/PersonApi.csproj
> Person ref attribute

- PersonApi/serverless.yml
Have personRef attribute on Get response object
> Deploy to staging and prod

- PersonApi/V1/Infrastructure/RefGeneratorEntity.cs
Add Datetime DynamoDB converter for lastmodified attribute
> Person ref
